baseURL = 'https://define9.github.io/'
languageCode = 'en-us'
title = 'define9 的博客'
description = "技术笔记与生活随想"
buildDrafts = true

[[module.imports]]
  path = "github.com/CaiJimmy/hugo-theme-stack/v4"
