backend:
  name: github
  repo: define9/define9.github.io
collections:
- fields:
  - label: Title
    name: title
    widget: string
  - label: Publish Date
    name: publish_date
    widget: datetime
  - label: Body
    name: body
    widget: richtext
  folder: content/posts
  icon: sell
  label: Blog
  media_folder: images
  name: blog
  path: '{{slug}}/index'
  public_folder: images
  summary: '{{title | upper}} — {{publish_date | date(''YYYY-MM-DD'')}} — {{body | truncate(20, ''...'')}}'
locale: zh-CN
media_folder: static/uploads
public_folder: /uploads
search: true
site_url: http://localhost:1313/
